drop table if exists member CASCADE;
create table member
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
-- sql 생성문 관리 해줌
-- h2 실행 -> ./h2.sh
-- select * from member; -> member 전체 데이터 조회
-- insert into member(name) values('spring') -> name 추가문